### ISSUE TITLE
"threads" value in profile.yml throws error when set by ENV variable

### ISSUE THREAD

**Issue by cabouffard** [fishtown-analytics/dbt-utils#108]
Hey, 

I’m hitting some kind of unexpected errors. I want the `thread` value of my `profiles.yml` file to be configurable via ENV variables, such as I can do the following:

```
default:
  outputs:
    dev:
      type: redshift
      threads: "{{ env_var('DEV_DBT_THREADS') }}" # [1-8]
      host: "{{ env_var('DEV_WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('DEV_WAREHOUSE_DB_PORT') }}"
      user: "{{ env_var('DEV_WAREHOUSE_DB_USER') }}"
      pass: "{{ env_var('DEV_WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('DEV_WAREHOUSE_DB_NAME') }}"
      schema: "{{ env_var('DEV_DBT_SCHEMA_OUTPUT') }}"
    staging:
      type: redshift
      threads: "{{ env_var('STAGING_DBT_THREADS') }}" # [1-8]
      host: "{{ env_var('STAGING_WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('STAGING_WAREHOUSE_DB_PORT') }}"
      user: "{{ env_var('STAGING_WAREHOUSE_DB_USER') }}"
      pass: "{{ env_var('STAGING_WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('STAGING_WAREHOUSE_DB_NAME') }}"
      schema: "{{ env_var('STAGING_DBT_SCHEMA_OUTPUT') }}"
    production:
      type: redshift
      threads: "{{ env_var('PRODUCTION_DBT_THREADS') }}" # [1-8]
      host: "{{ env_var('PRODUCTION_WAREHOUSE_DB_HOST') }}"
      port: "{{ env_var('PRODUCTION_WAREHOUSE_DB_PORT') }}"
      user: "{{ env_var('PRODUCTION_WAREHOUSE_DB_USER') }}"
      pass: "{{ env_var('PRODUCTION_WAREHOUSE_DB_PASSWORD') }}"
      dbname: "{{ env_var('PRODUCTION_WAREHOUSE_DB_NAME') }}"
      schema: "{{ env_var('PRODUCTION_DBT_SCHEMA_OUTPUT') }}"
  target: "{{ env_var('DBT_TARGET') }}"
```

Unfortunately, when building the docs I’m raised with the following error:

```
pipeline-dbt-docs | Encountered an error while reading profiles:
pipeline-dbt-docs |   ERROR Runtime Error
pipeline-dbt-docs |   Runtime Error
pipeline-dbt-docs |     Invalid arguments passed to "ProfileConfig" instance: threads.'4' is not of type 'number'
pipeline-dbt-docs | Defined profiles:
pipeline-dbt-docs |  - default
```

I dug a little bit, and saw that `env_var` was a macro defined by [this](https://github.com/fishtown-analytics/dbt/blob/dcc017d681c3e0a84555846f60db9443246ea206/dbt/context/common.py#L155) that uses `os.environ`. In this context, `os.environ` will always return a string.

I then dug into how the validation was being done and found [this](https://github.com/fishtown-analytics/dbt/blob/dcc017d681c3e0a84555846f60db9443246ea206/dbt/contracts/project.py#L314 ) which expects the value to be a number.

I'm unsure how to properly resolve that other than currently hard-coding a value to something.

I wanted to flag and document this error as this seems to be something that should be fixed.
Thanks!
