### ISSUE TITLE
dbt Minor Release Follow up for dbt-utils v0.6.0

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt-utils#273]
## Process for each dependent package
First, check if this is a breaking change
- [ ] Increase the upper bound of the `dbt-utils` `version:` config in the `packages.yml` of the dependent package, e.g.:
```yml
# packages.yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.0", "<0.7.0"]

```
- [ ] Push to a new branch to see if tests pass

If this is _not_ a breaking change:
- [ ] Create a patch release

If this _is_ a breaking change:
- [ ] Fix any breaking changes
- [ ] Increase the lower bound to the current dbt-utils minor version
- [ ] Create a minor release for the package

## Checklist of dependent packages
| package | PR | Release |
|--|:--:|:--:|
| [audit-helper](https://github.com/fishtown-analytics/dbt-audit-helper) | [Merged](https://github.com/fishtown-analytics/dbt-audit-helper/pull/26) | [0.3.0](https://github.com/fishtown-analytics/dbt-audit-helper/releases/tag/0.3.0) |
| [codegen](https://github.com/fishtown-analytics/dbt-codegen) | [Broken PR](https://github.com/fishtown-analytics/dbt-codegen/pull/31) | [0.3.0](https://github.com/fishtown-analytics/dbt-codegen/releases/tag/0.3.0) |
| [redshift](https://github.com/fishtown-analytics/redshift) | [Merged](https://github.com/fishtown-analytics/redshift/pull/37) | [0.4.1](https://github.com/fishtown-analytics/redshift/releases/tag/0.4.1) |
| [event-logging](https://github.com/fishtown-analytics/dbt-event-logging) | [Merged](https://github.com/fishtown-analytics/dbt-event-logging/pull/35) | [0.4.1](https://github.com/fishtown-analytics/dbt-event-logging/releases/tag/0.4.1) |
| [snowplow](https://github.com/fishtown-analytics/snowplow) | [PR](https://github.com/fishtown-analytics/snowplow/pull/97) | [0.12.0](https://github.com/fishtown-analytics/snowplow/releases/tag/0.12.0) |
| [external-tables](https://github.com/fishtown-analytics/dbt-external-tables) | [Merged](https://github.com/fishtown-analytics/dbt-external-tables/pull/40) | [0.5.0](https://github.com/fishtown-analytics/dbt-external-tables/releases/tag/0.5.0) |
| [segment](https://github.com/fishtown-analytics/segment) | [Merged](https://github.com/fishtown-analytics/segment/pull/60) | [0.5.1](https://github.com/fishtown-analytics/segment/releases/tag/0.5.1) |
| [facebook-ads](https://github.com/fishtown-analytics/facebook-ads) | [Merged](https://github.com/fishtown-analytics/facebook-ads/pull/39) | [0.6.0](https://github.com/fishtown-analytics/facebook-ads/releases/tag/0.6.0) |
| [stitch-utils](https://github.com/fishtown-analytics/stitch-utils) | [Merged](https://github.com/fishtown-analytics/stitch-utils/pull/17) | [0.2.1](https://github.com/fishtown-analytics/stitch-utils/releases/tag/0.2.1) |

**Comment by sethwoodworth** [comment]
Currently, dbt_utils 0.6.0 isn't installable with dbt 0.18.0:
```
$ dbt deps
Running with dbt=0.18.0
Encountered an error:
Version error for package fishtown-analytics/dbt_utils: Could not find a satisfactory version from options: ['=0.6.0', '>=0.4.0', '<0.6.0']
```

packages.yml:
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.0
  - package: fishtown-analytics/logging
    version: 0.4.0
```

**Comment by clrcrl** [comment]
You'll need to use logging `0.4.1`:

```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.0
  - package: fishtown-analytics/logging
    version: 0.4.1
```
