### ISSUE TITLE
Schema Test - Accepted Values for null value

### ISSUE THREAD

**Issue by ddppi** [fishtown-analytics/dbt-utils#287]
Hi, in one of my schema test, I want to test if the accepted values for a column is a list of numbers, or NULL, for example
models:
  - name: <model name>
    columns:
      - name: <column name>
        tests:
          - accepted_values:
                values: [0, 1, 99, null]

I find DBT tries to convert the value of the accepted values to characters, and also covert null to None. Then the test failed, because 
`Numeric value 'None' is not recognized`

Is this an issue?

I am using Snowflake, Python 3.7 and DBT v0.18.0. 

Thanks

**Comment by clrcrl** [comment]
Instead, you should use two separate tests:
```
version: 2

models:
  - name: my_model
    columns:
      - name: id
        tests:
          - accepted_values:
              values: [0, 1, 99]
          - not_null
```
