### ISSUE TITLE
dbt deps hangs in CI/CD - request to add proxy

### ISSUE THREAD

**Issue by josecolella** [fishtown-analytics/dbt-utils#356]
### Describe the feature

Currently the dbt deps command is hanging in Jenkins, as dependencies can only be installed from an artifactory cache.

### Describe alternatives you've considered

Is it possible to add an option to fetch the dependencies from a proxy source

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

### Who will this benefit?

This will benefit organizations that have to use proxy to install their dependencies

### Are you interested in contributing this feature?

Yes

**Comment by clrcrl** [comment]
Hi JOse — can you share the contents of your `packages.yml` file?

**Comment by josecolella** [comment]
Hello @clrcrl ,

Here are the contents:

```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
  - package: fishtown-analytics/dbt_external_tables
    version: 0.6.2
  - package: fishtown-analytics/redshift
    version: 0.4.1
```
