### ISSUE TITLE
get_query_results_as_dict() returns the column names instead of column contents

### ISSUE THREAD

**Issue by mg-matt** [fishtown-analytics/dbt-utils#359]
### Steps to reproduce

per the usage instructions, I run `{% set my_dict = dbt_utils.get_query_result_as_dict("SELECT * FROM " ~ ref(my_table))`
and it returns a list of all the columns in the table. Potentially of note here, my_table is a csv seed file in my instance.

### Expected results

I expect to return a dictionary with the contents of the query. for example:
Table:  
column_1, column_2
a,0
b,1
c,2

should return: {a:0, b:1, c:2}

### Actual results

using the example above, I get:
[column_1, column_2]

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
  - package: fishtown-analytics/stitch_utils
    version: 0.2.1

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
  - package: fishtown-analytics/stitch_utils
    version: 0.2.1

```
