### ISSUE TITLE
Add recency_where test

### ISSUE THREAD

**Issue by arndkorn** [fishtown-analytics/dbt-utils#364]
### Describe the feature
As a user I want to configure a recency test to run only on some days and to pass by default on others.

### Describe alternatives you've considered
I considered combining elements of the recency and the unique_where tests and came up with a schema test macro copied below.

### Additional context
When testing the recency of data generated in manual processes on working days (Mon-Fri) it would be good to avoid alert noise when no new data is expected (Sat-Sun).

### Who will this benefit?
This will help users who need recency tests for data expected to go stale over the weekend.

### Are you interested in contributing this feature?
Yes. It would be great to have feedback on this suggested code and documentation snippet:

```
{% macro test_recency_where(model, column_name, datepart, interval, where) %}
  -- schema test combining dbt-utils recency and test_unique_where

  select
    case when count(*) > 0 then 0
      {% if where %} when not {{ where }} then 0 {% endif %}
      else 1
      end as error_result
  from {{model}}
  where
    {{column_name}} >=
      {{dbt_utils.dateadd(datepart, interval * -1, dbt_utils.current_timestamp())}}

{% endmacro %}
```

This schema test asserts that there is data in the referenced model at least as recent as the defined interval prior to the current timestamp for a subset of rows by specifying a `where` clause.

Usage:

```
version: 2

models:
  - name: model_name
    tests:
      - dbt_utils.recency_where:
          datepart: day
          field: created_at
          interval: 1
          where: 'date_part(dow, current_date) between 2 and 6'
```
