### ISSUE TITLE
#313 Introduces a breaking change in `expression_is_true`

### ISSUE THREAD

**Issue by Ofir-Purple** [fishtown-analytics/dbt-utils#370]
### Describe the bug
PR #313 introduces a breaking change in `expression_is_true`. Before the change, it was possible to use the schema test on a column like so:

```yaml

- name: my_col
  tests:
    - dbt_utils.expression_is_true:
       expression: "my_col::VARCHAR NOT IN  ('[]', '{}')"
```

This is just a toy example, but it used to work. Even though you could've put the test in the model tests, it would still be useful to associate a test with a specific column from time to time.

The change in the PR breaks the above test because now the column name is added to the beginning of the expression which creates invalid SQL syntax.

### Steps to reproduce

Use the example above.

### Expected results

Expected minor version to not introduce breaking changes. This basically broke our build.

### Actual results

As described above.

### Screenshots and log output

```
syntax error at or near "my_col"
LINE 18:     where not(my_col my_col::VARCHAR NOT IN  ('[]', '{}'))
```

### System information

`packages.yml` file:
```yaml
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.0", "<0.7.0"]
```

**Which database are you using dbt with?**
- [V] postgres

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.19.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - redshift: 0.18.1
  - snowflake: 0.18.1
  - postgres: 0.18.1
  - bigquery: 0.18.1
```

### Additional context
It's this line in the PR: https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/schema_tests/expression_is_true.sql#L25

**Comment by clrcrl** [comment]
Hi @Ofir-Purple — thanks for the bug report.

It is indeed unfortunate that we managed to introduce an breaking change on a patch release — we didn't anticipate that this would be a breaking change as we'd previously only documented this as a _model_-level test (not a column-level test), and weren't aware that anyone was using it in that way.

Since there's a number of workarounds, I am going to close out this issue as a `wontfix`.

Workarounds (any of these should work):
1. Pin your utils version to `0.6.4`
2. Move the column-level test up to the model:

```yaml
- name: my_model
  tests:
    - dbt_utils.expression_is_true:
       expression: "my_col::VARCHAR NOT IN  ('[]', '{}')"
  columns:
    - name: my_col
```

Again — this was an unfortunate outcome, and definitely not expected behavior for a patch release. Apologies about that
