### ISSUE TITLE
combination_of_columns errors with takes no keyword argument 'column_name' on 0.7.0

### ISSUE THREAD

**Issue by joshuataylor** [fishtown-analytics/dbt-utils#383]
### Describe the bug
When following https://github.com/fishtown-analytics/dbt-utils#unique_combination_of_columns-source :

```
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns:
          - month
          - product
```

It shows an error:
```
Encountered an error:
Compilation Error in test dbt_utils_unique_combination_of_columns_xxxxx__col1__col2 (models/marts/foo/bar.yml)
  macro 'dbt_macro__test_unique_combination_of_columns' takes no keyword argument 'column_name'
```

Upgrade to 0.7.0 with 0.20.0, I can see the file changed so something must have broken.

### Steps to reproduce
Use the test in the examples.

### Expected results
It works? :)

### Actual results
It does not, and shows the above error.

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.7.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0-rc1
   latest version: 0.19.1

Your version of dbt is ahead of the latest release!

Plugins:
  - postgres: 0.20.0rc1
  - redshift: 0.20.0rc1
  - snowflake: 0.20.0rc1
  - bigquery: 0.20.0rc1
```

**Comment by jtcohen6** [comment]
Hey @joshuataylor, it sounds like you're specifying the `unique_combination_of_columns` test on a column, e.g.
```yml
models:
  - name: my_model
    columns:
      - name: my_column
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - month
                - product
```

The test only works (and is [only documented to work](https://github.com/fishtown-analytics/dbt-utils#unique_combination_of_columns-source)) when specified on a model-level (or source, snapshot, seed):
```yml
models:
  - name: my_model
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - month
            - product
```
