### ISSUE TITLE
[Bug] tests are propagated when downstream model has test using `source()` or `ref()` on upstream model

### ISSUE THREAD

**Issue by rightx2** [fishtown-analytics/dbt-utils#854]
### Describe the bug
1. sources.yaml

```
version: 2

sources:
  - name: my_source
    tables:
      - name: raw_customers
        columns:
          - name: id
            tests:
              - not_null               
      - name: raw_payments
```      

2. models/schema.yaml
```
version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - dbt_utils.relationships_where:
              to: source('my_source', 'raw_customers')
              field: id
```             

When I run  `dbt test --select source:my_source.raw_customers`, it trigger TWO TESTS, not one test:
- `dbt_utils_relationships_where_stg_customers_customer_id__id__source_my_source_raw_customers`
- `source_not_null_my_source_raw_customers_id`

### Steps to reproduce
Explained above

### Expected results
Only `source_not_null_my_source_raw_customers_id` run.

### Actual results
Below two run
- `dbt_utils_relationships_where_stg_customers_customer_id__id__source_my_source_raw_customers`
- `source_not_null_my_source_raw_customers_id`

### Screenshots and log output
```
INFO - [0m05:12:44  1 of 2 START test dbt_utils_relationships_where_stg_customers_customer_id__id__source_my_source_raw_customers_  [RUN]
INFO - [0m05:12:44  1 of 2 ERROR dbt_utils_relationships_where_stg_customers_customer_id__id__source_my_source_raw_customers_  [[31mERROR[0m in 0.01s]
INFO - [0m05:12:44  2 of 2 START test source_not_null_my_source_raw_customers_id ................... [RUN]
INFO - [0m05:12:44  2 of 2 PASS source_not_null_my_source_raw_customers_id ......................... [[32mPASS[0m in 0.02s]
INFO - [0m05:12:44
```

### System information
**The contents of your `packages.yml` file:**
Nothing

**Which database are you using dbt with?**
- [O] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [O] other (specify: impala)

**The output of `dbt --version`:**
```
- dbt=1.6.6
- dbt-postgres==1.6.6
```

### Additional context
The reason might be `source('my_source', 'raw_customers')` used in `stg_customers` model's test..(right?)
But I don't understand why `dbt_utils_relationships_where_stg_customers_customer_id__id__source_my_source_raw_customers` has to be triggered when targeting JUST `source:raw_customers`....

Is there any way to make it test run only `source_not_null_my_source_raw_customers_id` when running `dbt test --select source:my_source.raw_customers`?

### Are you interested in contributing the fix?
Yes if i could. Letting me know where to start will be helpful
